# PostgreSQL configuration for development

# Connection Settings
listen_addresses = '*'
max_connections = 100

# Memory Settings
shared_buffers = 128MB

# Locale / Timezone
datestyle = 'iso, mdy'
timezone = 'Etc/UTC'
log_timezone = 'Etc/UTC'
